### ISSUE TITLE
MultiCall requests have been deprecated, use individual requests instead.

### ISSUE THREAD

**Issue by aclark4life** [aclark4life/vanity#66]
(Due to warehouse launch)

```
Traceback (most recent call last):
  File "/usr/local/bin/vanity", line 11, in <module>
    sys.exit(vanity())
  File "/usr/local/lib/python3.6/site-packages/vanity.py", line 234, in vanity
    pattern=args.pattern)
  File "/usr/local/lib/python3.6/site-packages/vanity.py", line 103, in count_downloads
    for urls, data in get_release_info([package], json=json):
  File "/usr/local/lib/python3.6/site-packages/vanity.py", line 182, in get_release_info
    for package, releases in get_releases(packages):
  File "/usr/local/lib/python3.6/site-packages/vanity.py", line 163, in get_releases
    result = mcall()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 882, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: 'ValueError: MultiCall requests have been deprecated, use individual requests instead.'>
```

**Comment by lukasschwab** [comment]
Same issue.

`python 2.7.15`
`vanity 2.2.2`

```
Traceback (most recent call last):
  File "/usr/local/bin/vanity", line 11, in <module>
    sys.exit(vanity())
  File "/usr/local/lib/python2.7/site-packages/vanity.py", line 234, in vanity
    pattern=args.pattern)
  File "/usr/local/lib/python2.7/site-packages/vanity.py", line 103, in count_downloads
    for urls, data in get_release_info([package], json=json):
  File "/usr/local/lib/python2.7/site-packages/vanity.py", line 182, in get_release_info
    for package, releases in get_releases(packages):
  File "/usr/local/lib/python2.7/site-packages/vanity.py", line 163, in get_releases
    result = mcall()
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -32500: 'ValueError: MultiCall requests have been deprecated, use individual requests instead.'>
```

**Comment by jcea** [comment]
Hitting this too. Any progress?

**Comment by aclark4life** [comment]
@jcea Unfortunately no, and combined with #22, this could be the death knell for vanity. 💀

**Comment by ItsAditya-xyz** [comment]
lol sorry for pumping this again. but i am still having this error lol

**Comment by filipporomani** [comment]
same

**Comment by hugovk** [comment]
Use one of these instead:

* https://pepy.tech/
* https://pypistats.org/
* https://github.com/hugovk/pypistats
* https://github.com/ofek/pypinfo
* https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/

**Comment by aclark4life** [comment]
RIP vanity
